### PR TITLE
Some enhancements to ansible-oracle

### PR DESCRIPTION
**Pull request by Rendanic**
I added a lot feautures to ansible-oracle. I'll delete my 1st pull request because this one will replace it. I reverted the change for removed item.1.stdout in role oraswdb-install as it was a wrong solution for the problem.

The added feautures:
- added lvsize to filesystem | create lv
This is an incompatble change. Sorry for that, but the old way with '100%FREE' is not working when ansible is called the 2nd time. I added another variable lvsize to fix this problem and added the possibility to created more then 1 logical Volume in the Volume Group. You could create /u01, /u01/app/oracle/diag etc. as different Filesystems in 1 Volume Group.
The incompatible Change is only for user who defined a custom variable for host_fs_layout and a physical Volume which is less then 14GB. The default is changed to a fixed size of 14GB for the filesystem. This should be enought for 1 Grid-Infrastructure and 1 ORACLE_HOME in a lab environment.

- Custom ORACLE_HOME for each Database
Add oracle_home to oracle_databases for custom ORACLE_HOME. oracle_home_db is used when no oracle_home is defined in oracle_databases.

- Custom Characterset for each database
Add characterset and/or nationalcharacterset in oracle_databases to define a custom characterset for each database. The old defaults are used when no value is defined in oracle_databases

- Bugfix for install_from_nfs
Installing without nfs wasn't possible. Thias has been fixed.

- dotprofile save against changed ORACLE_HOME in oratab
The ORACLE_HOME is not fixed anymore. It is determined from oratab when possible. Otherwise the old behavior with a fixed value is used.. This makes dotprofile reliable against changes for ORACLE_HOME in oratab.

- added some tags in oradb-create and oraswgi-install
I added a lot of tags to the 1st task in each role. The tags are required due to dependency between subtasks and the 1st task.

- changes in gloginsql could be disabled
Define configure_gloginsql=False to disable changing the gloginsql. The file will be change by default.

- better detection of ORACLE_SID in oratab
I changed the searchstring, because a # in from of an entry wasn't ignored.

- added lsasmlib
I added some tags in role orahost-storage. An -t lsasmlib could be used to get information for the Disks from oracleasm.

### CODE REVIEW

**Comment by oravirt** [comment]
Hi,
I'll go through this as soon as possible.
Re: the lvol issue - the 100%FREE has always worked, but there was a regression in the lvol module a while back which caused this behavior. I only noticed in in 2.1 though. https://github.com/ansible/ansible-modules-extras/issues/428 talks about this
There is a fix for it coming in 2.2, and in the meantime you could pull down the latest lvol.py and put that in a 'library' folder and that will fix the issue.

I'actually working on a new layout for the host_fs_layout which will allow for multiple disks per VG etc, so I'll have to see how this fits in. I'm all for having the lvsize configurable though.

I'll let you you know as soon as possible.

Thanks a lot for getting involved!

**Comment by Rendanic** [comment]
Hello Mikael,
thanks for the fast response. You should add a parameter for lvsize, so
there is a way to configure the size of the lvol. We need that for volume
groups with different number of lvols.

I am fine with a new layout of host_fs_layout.My changes were really small.

Kinde Regards
Thorsten Bruhns


2016-07-09 10:16 GMT+02:00 Mikael Sandström <notifications@github.com>:

**Comment by oravirt** [comment]
Ok - sorry about the delay, I'm on vacation so my priorities are elsewhere at the moment ;-)

I pulled down the pullrequest2 branch and ran through a couple of tests and these are the issues I ran into.

- custom ORACLE_HOME
oradb-create fails if run a second time, if using a custom ORACLE_HOME (it should just skip the create-part if the db already exists).
The first task checks for the default home + oracle_db_name and uses that for deciding whether or not to create the db. In this case it causes the dbca to run again, which then fails because the db actually already exists (but with a custom home).
There should probably be another/separate check for custom home + oracle_db_name and use that as the conditional for the 'custom create db' task.

oraswdb-install runs root.sh every time for a custom home, since it doesn't find that home in the inventory (it also only checks against the default home and not the custom home).

However, I also think that I should've made the oratab-check more robust from the start. I only check for !=1, should probably be something like == 0

And even though it was possible to use a separate home for each database home previously, there was no easy way of separating by mountpoints etc, so this functionality is most welcome!


- the conditional for glogin (configure_gloginsql + oracle home ) is targeting variables incorrectly.
You only have 1 list in with_items, so item.0.oracle... will not work. It should be item.oracle_ .....
As a result of that, this never e

- dotprofile_db doesn't use the same template for oraswdb-install & oradb-create, which means it gets overwritten as the profile may be updated (with the original/old template) after the db is created.

- update oratab:
This is only meant to be run if the oracle_db_type != 'SI' (mostly to get the instances in oratab when running RAC). It has been changed to == 'SI', so it will run under the wrong conditions.
This causes confusion the second time oradb-create is run, since the initial check (which checks oratab) will then return 2 and then try to run again and fail. However, this goes back to the first point of making the initial check more robust.

Also, the actual task to update oratab (lineinfile) should be changed. Since the combination of db+oracle_home is already there (as part of the dbca-run) it shouldn't be added again. That is something I've been meaning to change for a while....

- NFS
The last task in oraswdb-install (that unmounts the nfs FS) should also have the install_from_nfs conditional added.
Also, What exactly did you mean by 'Installing without nfs wasn't possible'?


- lvsize
I'll probably raise the default to 50G, as the default way of installing is pushing the installationfiles to the db-host (by default to /u01/stage), and then 14G probably won't be enough if in its own FS

I haven't had time to run through a RAC-installation so there is possibility some things may come up with regards to that, but most of these things are valid for either type of installation.
I'll do a RAC config when I get the time.

**Comment by Rendanic** [comment]
Thanks for the detailed answer on this pull request. I opened some Issues to track the details of this pull request and I think it is a better idea to do it step by step and not as a huge pull request.
I find a huge failure on my side, which is part of this pull request. I did most of the changes for custom ORACLE_HOME the wrong way. I didn't know, that I could do this with a small change in dafaults/main.yml by changing the definition of oracle_home_db and fixing some tasks.
After we clarified the details, I'll rewrite the changes and create a new pull requst for them.

**Pull request closed without merging**
