### PR TITLE
Fix for issue #379.

### PR DESCRIPTION
**Pull request by talek**

### CODE REVIEW

**Review by Rendanic — COMMENTED** [review]
Are the addional variables in `default/main.yml` really needed?
`oradb_manage_statspack` has a dependency to `orasw_meta` where the variables are already defined.

**Comment by talek** [comment]
I think those `orasw_meta` variables can be refactored to cope with the way PDB(s) are being looped over in the `oradb_manage_statspack`, but I've chosen not to complicate even further `orasw_meta` variables definition and go with a more narrow scope of the change, affecting just the `oradb_manage_statspack` role.

**Comment by Rendanic** [comment]
I released 4.0.0b1 today. That has lot of refactorings in it and hopefully fixed that.
It is not production ready at the moment due to massive amount of changes.,

Please change the PR target to branch `release/3.x` if we want to fix it in 3.x.

**Comment by Rendanic** [comment]
Closing PR.

**Pull request closed without merging**
